config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  get "/borrow_book" => 'books#borrow_book', as: 'borrow_book'

  root 'books#index'

  get 'qunachi', to: 'misc#qunachi'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books=BOOKS::ALL
  end

  def borrow_book
    # @selected = Item.where(:category_id => params[:cat_id])
    book_id = params[:book_id] || 'https://book.douban.com/subject/10768068'
    @book = BOOKS::ALL.select {|book| book[:url].include? book_id  }.first
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :url, :rating, :ratings_num, :image_url)
    end
end

app/controllers/misc_controller.rb
class MiscController < ApplicationController

  def youdu
    @books=BOOKS::ALL

    @reviews =
    [
        {user:'旗帜', likes: 22,
         content:
             '20160609-20160708。本书只是讲了耐克草创时期的人和事。他害羞内向的性格，他无限热爱的事业，他的志同道合的朋友们，他的感情史，他面对竞争对手的害怕和绝地反击。作者一直说他害羞，其实书中不乏笑点，想必也是一个闷骚男。'
        },
        {user:'W', likes: 31,
         content:'耐克创始人回忆录，一群shoe dogs的坚持成就了今日的耐克。耐克前18年是跌宕起伏的18年，与鬼冢虎的恩恩怨怨，与银行的博弈现金流的枯竭，甚至遇到政治阻力，精彩纷呈。1962年，奈特先生去日本Kobe(神户)与鬼冢株式会社谈判代理Tiger牌运动鞋事宜，后来科比和老虎都成为耐克最具影响力的代言人，冥冥之中有天意'
        }]

  end



  def qunachi

  end

  def tjhot
    @page_title = 'TJ Hot'
    params[:sort] ||= 'hot'
    articles = YAML.load_file('articles2.yaml').sort_by { |x| x[:time] }.reverse
                   .select{ |x| x[:time]> 7.days.ago}
    @last_update_time =articles.first[:time]
        if params[:sort] == 'new'
      @articles = articles.sort_by { |x| x[:time] }.reverse
    else
      @articles = articles.select{ |x| x[:read_number].presence && x[:read_number] > 200 }.sort_by { |x| x[:read_number] }.reverse
    end
    @articles=@articles.first(75)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def num_to_star(num)
    num
  end

  MOBILE_USER_AGENTS =  'palm|blackberry|nokia|phone|midp|mobi|symbian|chtml|ericsson|minimo|' +
      'audiovox|motorola|samsung|telit|upg1|windows ce|ucweb|astel|plucker|' +
      'x320|x240|j2me|sgh|portable|sprint|docomo|kddi|softbank|android|mmp|' +
      'pdxgw|netfront|xiino|vodafone|portalmmm|sagem|mot-|sie-|ipod|up\\.b|' +
      'webos|amoi|novarra|cdm|alcatel|pocket|iphone|mobileexplorer|mobile'

  def mobile?
    agent_str = request.user_agent.to_s.downcase
    return false if agent_str =~ /ipad/
    agent_str =~ Regexp.new(MOBILE_USER_AGENTS)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div class="book" data-markerid="<%= book[:marker_id] %>">
  <div class="row">
    <div class="book-cover col-sm-3">
      <%= link_to book[:url], target: '_blank' do %>
        <%= image_tag(book[:cover], class:"img-responsive" ) %>
      <% end %>
    </div>
    <div class="book-info col-sm-9">
      <h3 class="book-title">
        <%= link_to book[:title], book[:url], target: '_blank', class:'inherit-color' %>
        <small class="inline-block"><%= book[:category] %></small>
      </h3>
      <div class="rating-info">
        <span class="rating"><%= book[:rating] %> </span>
        <span class="rating-right text-info">
          <span class="star<%= book[:rating].ceil %> star-img"> </span>
          <small><%= book[:ratings_num] %>人评价</small></span>
      </div>

      <% book[:reviews].each do |review| %>
        <div class="review">
          <span class="user">
            <%= link_to(review[:user], review[:user_url], target: '_blank') %>:
            <%= review[:content] %>
          </span>
          <span class="likes pull-right">
            <small>
              <%= fa_icon "thumbs-o-up" %> <%= review[:likes] %>
            </small>
          </span>
        </div>
      <% end %>
      <div class="borrow-info">
        <% if book[:borrow_info][:avaiable]  %>
          <div class="user-info">
            <% borrower = book[:borrow_info][:borrower]  %>
            <%= link_to borrower[:user_url] do %>
                <%= image_tag(borrower[:avatar], class: 'img-round pull-left avatar' ) %>
            <% end %>
            <h4 class="pull-left">
              <%= link_to borrower[:user_name], borrower[:user_url], target: '_blank', class:'inherit-color' %> 有这本书
              <br>
              <small>附近<%= borrower[:distance] %>m, <%= borrower[:record_num] %>人借过</small>
            </h4>
          </div>
          <div class="btn-group pull-right action-button" >
            <%= link_to '借', borrow_book_path(book_id: book[:url].split('/')[-1]), remote: true, class: 'btn btn-primary btn-lg',
                        data: {toggle: 'modal', target: '#myModal'}, book_id: book[:url] %>
            <%= link_to '在线试读', book[:sample_url], class: "btn btn-default btn-lg", target: '_blank' %>
          </div>
        <% else  %>
          <% wishers = book[:borrow_info][:wishers]  %>
          <div class="user-info">
            <% wishers.each do |wisher| %>
                <%= link_to wisher[:user_url], target: '_blank', class: 'wisher pull-left' do %>
                    <%= image_tag(wisher[:avatar], class: 'img-round avatar' ) %>
                <% end %>
            <% end  %>
            <h4 class="pull-left">
              <%= link_to wishers.first[:user_name], wishers.first[:user_url], target: '_blank', class:'inherit-color' %> 等<%= wishers.count %>人想读
              <br>
              <small>附近 <%= wishers.first[:distance]  %>m</small>
            </h4>
          </div>
          <div class="btn-group pull-right action-button" >
            <%= link_to '我有', book[:url], class: 'btn btn-success btn-lg', target: '_blank' %>
            <%= link_to '想读', book[:url], class: 'btn btn-default btn-lg', target: '_blank' %>
          </div>
        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/books/_book_temp.html.erb
<div class="book ">
  <div class="row">
    <div class="book-cover col-md-3">
      <a href="https://book.douban.com/subject/26934189/" target="_blank">
        <img src="https://img3.doubanio.com/lpic/s29215340.jpg" alt="A Man for All Markets" class="img-responsive" >
      </a>
    </div>
    <div class="book-info col-md-9">
      <h3 class="book-title">
        <a href="https://book.douban.com/subject/26934189/" target="_blank" class="inherit-color">
          A Man for All Markets
        </a>
      </h3>
      <div class="rating-info">
        <span class="rating">8.8 </span>
              <span class="rating-right text-info">
                <span class="star9 star-img"> </span>
                <small>19人评价</small></span>
      </div>
      <div class="category">
        投资 / 金融 / 传记
      </div>

      <% @reviews.each do |review| %>
          <div class="review">
              <span class="user">
                <a href=""><%= review[:user] %></a>:
                <%= review[:content] %>
              </span>
              <span class="likes pull-right">
                <small>
                  <a href=""><%= fa_icon "thumbs-o-up" %></a> <%= review[:likes] %>
                </small>
              </span>
          </div>
      <% end %>
      <div class="review">
              <span class="user">
                <a href="">子珂</a>: 半本好书，前面挺有意思，讲他如何少年时的读书生涯，如何在几个专业间流转，如何解出21点，如何成为最早的quant并建立自己的hedge fund。
                可惜后面部分行文太过随意，没什么有深度的东西了
                <a href="">...<small>阅读全文</small></a>
              </span>
              <span class="likes pull-right">
                <small>
                  <a href=""><%= fa_icon "thumbs-o-up" %></a> 62
                </small>
              </span>
      </div>

      <div class="borrow-info">
        <a href="https://www.douban.com/people/4581134/" target="_blank">
          <img src="https://img3.doubanio.com/icon/ul4581134-5.jpg"
               class="img-round pull-left avatar" height="64" width="64">
        </a>
        <h4 class="pull-left">
          <a href="https://www.douban.com/people/4581134/" target="_blank" class="user-name inherit-color">Ginsa</a>
          有这本书
          <br>
          <small>附近1km, 3人借过</small>
        </h4>
        <div class="btn-group pull-right action-button" >
          <%= link_to '借', borrow_book_path(book_id: 'test'), :remote => true,
                      class: 'btn btn-primary btn-lg btn-borrow', 'data-toggle': 'modal', 'data-target': '#myModal' %>
          <a href="https://read.douban.com/reader/ebook/31842175/" target="_blank"
             class="btn btn-default btn-lg btn-read">在线试读</a>
        </div>
      </div>
    </div>
  </div>



</div>

app/views/books/_borrow_modal.html.erb
<% user=book[:borrow_info][:borrower]  %>
<div class="modal-dialog " role="document">
  <div class="modal-content borrow-modal">
    <div class="modal-header user">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title text-center">
        <%= link_to user[:user_url], target: '_blank', class: 'avatar-wrapper' do %>
            <%= image_tag(user[:avatar], class: 'img-round avatar') %>
        <% end %>
        <%= link_to user[:user_name], user[:user_url], class: 'inherit-color' %>
      </h4>
    </div>
    <div class="modal-body book-info">
      <div class="row">
        <div class="book-cover col-xs-3">
          <%= link_to book[:url], target: '_blank' do %>
              <%= image_tag(book[:cover], class:"img-responsive" ) %>
          <% end %>
        </div>
        <div class="col-xs-9">
          <h4 class="book-title"><%= link_to book[:title], book[:url], class: 'inherit-color'%></h4>
          <label>地点:</label> <span>酒仙桥 <%= user[:distance] %>m附近</span>
          <br>
          <label>时长:</label> <span>1 周</span>
          <br>
          <label>费用:</label> <span>1 元 (+ 保险 0.2 元)</span>
          <br>
          <br>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#testModal">找TA借书</button>

        </div>
      </div>
    </div>
    <div class="modal-body message-box">
    </div>
    <div class="modal-footer send-message">
      <form class="form-inline">
        <div class="form-group">
          <input class="form-control" placeholder="Hi, <%= user[:user_name] %>, 这本书怎么样？">
        </div>
        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#testModal">发送</button>
      </form>
    </div>
  </div>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :book_url %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating, id: :book_rating %>
  </div>

  <div class="field">
    <%= form.label :ratings_num %>
    <%= form.number_field :ratings_num, id: :book_ratings_num %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :book_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/_map.html.erb
  <div id="mapid"></div>
  <script type="text/javascript" src="http://webapi.amap.com/maps?v=1.3&key=63e43a31483260743e7740a75896a51a"></script>
  <script src="//webapi.amap.com/ui/1.0/main.js"></script>
  <script type="text/javascript">
    lat = 39.974291;
    long =  116.490344;
    var mapObj  = new AMap.Map('mapid',{
      resizeEnable: true,
      zoom: 14,
      center: [long, lat]
    });

//    marker = new AMap.Marker({
//      position: [long, lat],
//      map: mapObj
//    });

    AMapUI.loadUI(['control/BasicControl'], function(BasicControl) {
      mapObj.addControl(new BasicControl.Zoom({
        position: 'lt'
      }));
    });

    function getRandomArbitrary(min, max) {
      return Math.random() * (max - min) + min;
    }

    var bookGeoInfoArray = [
      <% @books.each_with_index do |book, i| %>
        <% if book[:borrow_info][:avaiable]  %>
          {number: <%= i+1 %>, position: [lat-0.005, long-0.01], item: '<%= book[:title] %>',
            book_id: '<%= book[:url].split('/')[-1] %>', marker_id: '<%= book[:marker_id] %>'},
        <% end %>
      <% end %>
    ];

    var arrayLength = bookGeoInfoArray.length;
    for (var i = 0; i < arrayLength; i++) {
      var bookGeoInfo = bookGeoInfoArray[i];
      var content = document.createElement('div');
      content.innerHTML =
        '<a class="book-marker" data-remote="true" data-toggle="modal" data-target="#myModal" href="/borrow_book?book_id='+ bookGeoInfo.book_id+'">' +
          '<div class="book-num ' +  bookGeoInfo.marker_id + '">'+
            bookGeoInfo.number +
          '</div>'+
          '<div class="item-info">'+bookGeoInfo.item+'</div>' +
          '</a>';
      content.className = 'map-icon';

      marker = new AMap.Marker({
        content: content,
        position: [long+getRandomArbitrary(-0.015, 0.015) , lat+getRandomArbitrary(-0.015, 0.015)],
        map: mapObj
      });
    }
  </script>
  <span class="glyphicon glyphicon-book"></span>

app/views/books/borrow_book.js.erb
 $("#myModal .modal-dialog").replaceWith("<%= escape_javascript(render partial: 'borrow_modal', locals: { book: @book } ) %>");

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div>
  <div class="books">
    <div class="row">
      <% @books.each_slice(2) do |book1, book2|  %>
        <div class="col-lg-12">
          <div class="col-xl-6">
            <%= render(partial: 'book', locals:{book: book1}) %>
          </div>
          <div class="col-xl-6">
            <%= render(partial: 'book', locals:{book: book2}) %>
          </div>
        </div>
      <% end  %>
    </div>

    <div class="pagination col-xs-12 text-center">
      <%= link_to '下一页', '#', class: 'btn btn-default btn-lg', data: {toggle: 'modal', target: '#testModal'} %>
    </div>

    <div class="col-xs-12 footer visible-xs-block">
      <span class="text-muted">
        什么是豆瓣有读？
      </span>
      <span class="text-muted pull-right">
        Made by <%= link_to '子珂', '#', target: '_blank' %>
      </span>
    </div>
  </div>

  <% if !mobile?  %>
    <div class="map hidden-xs">
      <%= render('map') %>
    </div>
  <%  end %>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <%= render(partial: 'borrow_modal', locals: { book: @books.first  }) %>
  </div>
  <div class="modal fade" id="testModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content">
        <div class="modal-body text-center">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4>产品还在内测中，你可以</h4>
          <%= link_to '申请测试', BOOKS::INTRO_LINK, class: 'btn btn-primary btn-lg', 'data-dismis': "modal", target: '_blank' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @book.url %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @book.rating %>
</p>

<p>
  <strong>Ratings num:</strong>
  <%= @book.ratings_num %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <h2 class="no-margin nav-title navbar-brand">
        <%= link_to(root_path, class:'inherit-color ') do %>
            <span class="first">豆瓣</span><span class="second">友</span><span class="third">读</span>
        <% end %>
        <small class="text-muted hidden-xs">目前仅支持北京酒仙桥地区</small>
      </h2>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to '申请测试', BOOKS::INTRO_LINK, target: '_blank' %></li>
      <li class="hidden-xs"><a href="https://github.com/cqcn1991/youdu" target="_blank"><%= fa_icon 'github' %> Github</a></li>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>豆瓣友读 - 找你的友邻借本书吧 ~</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env == 'production' %>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-48003175-6', 'auto');
          ga('send', 'pageview');

        </script>
    <% end %>
  </head>

  <body>
 <%= render 'layouts/header' %>
  <%= yield %>
  </body>
</html>

app/views/misc/_book.html.erb
<div class="book" data-markerid="<%= book[:marker_id] %>">
  <div class="row">
    <div class="book-cover col-md-3">
      <a><%= image_tag(book[:cover], class:"img-responsive" ) %></a>
    </div>
    <div class="book-info col-md-9">
      <h3 class="book-title"><%= book[:title] %></h3>
      <div class="rating-info">
        <span class="rating"><%= book[:rating] %> </span>
        <span class="rating-right text-info">
          <span class="star<%= book[:rating].ceil %> star-img"> </span>
          <small><%= book[:ratings_num] %>人评价</small></span>
      </div>
      <div class="category">
        <%= book[:category] %>
      </div>

      <% book[:reviews].each do |review| %>
          <div class="review">
            <span class="user">
              <a href=""><%= review[:user] %></a>:
              <%= review[:content] %>
            </span>
            <span class="likes pull-right">
              <small>
                <a href=""><%= fa_icon "thumbs-o-up" %></a> <%= review[:likes] %>
              </small>
            </span>
          </div>
      <% end %>
      <div class="borrow-info">
        <% if book[:borrow_info][:avaiable]  %>
            <% borrower = book[:borrow_info][:borrower]  %>
            <%= image_tag(borrower[:avatar], class: 'img-round pull-left avatar' ) %>
            <h4 class="pull-left">
              <%= borrower[:user_name] %> 有这本书
              <br>
              <small>附近<%= borrower[:distance] %>m, <%= borrower[:record_num] %>人借过</small>
            </h4>
            <div class="btn-group pull-right borrow-button" >
              <button type="button" class="btn btn-primary btn-lg"
                      data-toggle="modal" data-target="#myModal">借</button>
              <button type="button" class="btn btn-default btn-lg"
                      data-toggle="modal" data-target="#myModal">在线试读</button>
            </div>
        <% else  %>
            <% wishers = book[:borrow_info][:wishers]  %>
            <% wishers.each do |wisher| %>
                <%= image_tag(wisher[:avatar], class: 'img-round pull-left avatar wisher' ) %>
            <% end  %>
            <h4 class="pull-left">
              <%= wishers.first[:user_name] %> 等<%= wishers.count %>人想读
              <br>
              <small>附近 <%= wishers.first[:distance]  %>m</small>
            </h4>
            <div class="btn-group pull-right borrow-button" >
              <button type="button" class="btn btn-success btn-lg">我有</button>
              <button type="button" class="btn btn-default btn-lg">+1</button>
            </div>
        <% end  %>
      </div>
    </div>
  </div>
</div>

app/views/misc/_borrow_modal.html.erb
<% user=book[:borrow_info][:borrower]  %>
<div class="modal-dialog " role="document">
  <div class="modal-content borrow-modal">
    <div class="modal-header user">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title text-center">
        <%= image_tag(user[:avatar], class: 'img-round avatar') %>
        <span class="user-name"><%= user[:user_name] %></span>
      </h4>
    </div>
    <div class="modal-body book-info">
      <div class="row">
        <div class="book-cover col-xs-2">
          <%= image_tag(book[:cover], class: "img-responsive") %>
        </div>
        <div class="col-xs-10">
          <button type="button" class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#testModal">找她借书</button>
          <h4 class="book-title"><%= book[:title] %></h4>
          <label>地点:</label> <span>酒仙桥 <%= user[:distance] %>m附近</span>
          <br>
          <label>时长:</label> <span>1 周</span>
          <br>
          <label>费用:</label> <span>1 元</span>
          <br>
        </div>
      </div>
    </div>
    <div class="modal-body message-box">
    </div>
    <div class="modal-footer send-message">
      <form class="form-inline">
        <div class="form-group">
          <input class="form-control" placeholder="Hi, <%= user[:user_name] %>, 这本书怎么样？">
        </div>
        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#testModal">发送</button>
      </form>
    </div>
  </div>
</div>

app/views/misc/qunachi.html.erb
<div class="qunachi-container">
  <div class="map">
    <%= render('map') %>
  </div>

  <div class="restaurants">
    <div class="multiple-items" data-slick='{"slidesToShow": 3, "slidesToScroll": 3}'>
      <% 4.times do %>
      <div class="restaurant">
        <img class="img-responsive" src="http://p1.meituan.net/merchantpic/311b9072de07363ed02ce06540826abb3337196.jpg%40280w_212h_1e_1c_1l%7Cwatermark%3D0" alt="">
        <h4>￥618 上海 - 整套房子/公寓</h4>
        <div class="restaurant-rating">
          <% 5.times do  %>
              <span class="star"><svg viewBox="0 0 1000 1000" aria-hidden="true" focusable="false" style="display: block; fill: currentcolor; height: 1em; width: 1em;"><path d="M971.5 379.5c9 28 2 50-20 67L725.4 618.6l87 280.1c11 39-18 75-54 75-12 0-23-4-33-12l-226.1-172-226.1 172.1c-25 17-59 12-78-12-12-16-15-33-8-51l86-278.1L46.1 446.5c-21-17-28-39-19-67 8-24 29-40 52-40h280.1l87-278.1c7-23 28-39 52-39 25 0 47 17 54 41l87 276.1h280.1c23.2 0 44.2 16 52.2 40z"></path></svg></span>
          <% end  %>
          <span>175条评价</span>
        </div>
      </div>
      <% end  %>
    </div>
  </div>
</div>